export const ADMIN_CONTACT_FAIL = "ADMIN_CONTACT_FAIL";
export const ADMIN_CONTACT_REQUEST = "ADMIN_CONTACT_REQUEST";
export const ADMIN_CONTACT_SUCCESS = "ADMIN_CONTACT_SUCCESS";
export const POST_CONTACT_REQUEST = "POST_CONTACT_REQUEST";
export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";
export const POST_CONTACT_FAIL = "POST_CONTACT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";